language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python bing_dorker.py  # Python2
  - python bing_dorker3.py # Python3
